MvcSpAppWeb/ViewModels/AboutViewModel.cs
using MvcSpAppWeb.Poco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcSpAppWeb.ViewModels
{
    public class AboutViewModel
    {
        private PictureUrl pictureUrl;
        public PictureUrl PictureUrl
        {
            get { return pictureUrl; }
            set { pictureUrl = value; }
        }

        private string displayName;
        public string DisplayName
        {
            get { return displayName; }
            set { displayName = value; }
        }

        private string email;
        public string Email
        {
            get { return email; }
            set { email = value; }
        }


        private int sharePointId;
        public int SharePointId
        {
            get { return sharePointId; }
            set { sharePointId = value; }
        }

        private string refreshToken;
        public string RefreshToken
        {
            get { return refreshToken; }
            set { refreshToken = value; }
        }

        private string accessToken;
        public string AccessToken
        {
            get { return accessToken; }
            set { accessToken = value; }
        }

        private string appOnlyAccessToken;
        public string AppOnlyAccessToken
        {
            get { return appOnlyAccessToken; }
            set { appOnlyAccessToken = value; }
        }

        private HostWebListCount hostWebListCount;
        public HostWebListCount HostWebListCount
        {
            get { return hostWebListCount; }
            set { hostWebListCount = value; }
        }



    }
}

MvcSpAppWeb/Controllers/HomeController.cs
using Microsoft.SharePoint.Client;
using MvcSpAppWeb.Models;
using System;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Text;
using MvcSpAppWeb.CodeHelper;
using System.Collections.Specialized;
using MvcSpAppWeb.Poco;
using MvcSpAppWeb.ViewModels;
using MvcSpAppWeb.Config;


namespace MvcSpAppWeb.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [SharePointContextFilter]
        public  ActionResult Index()
        {

            #region Constantes

            /*Ici une constante designant le produit SharePoint*/
            string SharePointPrincipal = "00000003-0000-0ff1-ce00-000000000000";

            /* Nom du paramètre SPHostUrl*/
            /*Ici la clef pour obtenir la valeur du site hote dans SharePoint cette valeur est contenue dans la requete initiale*/
            var SPHostUrlKey = "SPHostUrl";

            /*Ici les clefs ID/Secret pour acceder aux valeurs du Web.config*/
            var webConfigId = System.Configuration.ConfigurationManager.AppSettings["ClientId"];
            var webConfigSecret = System.Configuration.ConfigurationManager.AppSettings["ClientSecret"];

            #endregion

            #region Variables Declarer un objet spUser qui contient quelques propriétés a mapper avec le User MVC correspondant
            HttpContext context = System.Web.HttpContext.Current;
            User spUser = null;
            #endregion

            #region Ici recuperer le spAppToken contenu dans la requete
            string SPAppToken = context.Request.Params.Get("SPAppToken");
            #endregion

            #region Ici demander au Token helper de valider que le spAppToken provient bien de la bonne plateforme. Penser a faire manuelement la validation du Token
            SharePointContextToken contextToken = TokenHelper.ReadAndValidateContextToken(SPAppToken, context.Request.Url.Authority);
            #endregion

            #region Ici extraire le refresh token
            string refreshToken = contextToken.RefreshToken;
            #endregion

            #region Recuper le DOMAINE de SharePoint , le GUID d'office 365 l'URL du Servive ACS qui peux delivrer un Access Token 
            /*Office 365 guid exemple d540fc2e-db24-4ad7-8c51-99f00b13f134*/
            string targetRealm = contextToken.Realm;
            /*Domaine du site Host Sharepoint exemple jeremycorp.sharepoint.com */
            string targetHost = context.Request.QueryString[SPHostUrlKey];
            Uri targetUri = new Uri(targetHost);
            targetHost = targetUri.Authority;

            /*SharePoint Principal+sp domain+office 365 guid*/
            string ressource = string.Format("{0}/{1}@{2}", SharePointPrincipal, targetHost, targetRealm);
            string targetPrincipalName = contextToken.TargetPrincipalName;

            /*Adresse de l'identity provider*/
            string securityTokenServiceUrl = TokenHelper.AcsMetadataParser.GetStsUrl(targetRealm);
            #endregion



            #region Grace a L'API Sharepoint on recupere le spUser Courrant
            /*Grace a L'API Sharepoint on recupere le spUser Courrant*/
            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {
                if (clientContext != null)
                {
                    spUser = clientContext.Web.CurrentUser;
                    clientContext.Load(spUser);
                    clientContext.ExecuteQuery();
                    ViewBag.UserName = spUser.Title;
                }
            }
            #endregion

            #region Encapsuler les informations
            /*Encapsuler les informations*/
            /*NameValueCollection */
            NameValueCollection userProperties = new NameValueCollection();
            userProperties.Add("RefreshToken", refreshToken);
            userProperties.Add("TargetRealm", targetRealm);
            userProperties.Add("Ressource", ressource);
            userProperties.Add("SecurityTokenServiceUrl", securityTokenServiceUrl);
            userProperties.Add("TargetHost", targetHost);
            userProperties.Add("TargetPrincipalName", targetPrincipalName);
            #endregion

            #region Read Tokens
            /*
            HttpWebRequest endpointRequest =(HttpWebRequest)HttpWebRequest.Create("https://jeremycorp.sharepoint.com/_api/web/siteusers?format=json");
            endpointRequest.Method = "GET";
            endpointRequest.Accept = "application/json;odata=verbose";
            endpointRequest.Headers.Add("Authorization",
              "Bearer " + accesToken);
            HttpWebResponse endpointResponse = (HttpWebResponse)endpointRequest.GetResponse();

            HttpWebRequest currentUserRequest = (HttpWebRequest)HttpWebRequest.Create("https://jeremycorp.sharepoint.com/_api/web/siteusers?$filter=UserId/NameId eq '10037ffe8c9efa88'&$format=json");
            currentUserRequest.Method = "GET";
            currentUserRequest.Accept = "application/json;odata=verbose";
            currentUserRequest.Headers.Add("Authorization",
              "Bearer " + accesToken);
            HttpWebResponse currentUserResponse = (HttpWebResponse)currentUserRequest.GetResponse();

            
            var data = context;

            string[] SPAppTokenTokenArray = SPAppToken.Split('.');
            byte[] SPAppTokenHeaderBytes = B64Helper.base64urldecode(SPAppTokenTokenArray[0]);
            byte[] SPAppTokenClaimsBytes = B64Helper.base64urldecode(SPAppTokenTokenArray[1]);
            SPAppToken = Encoding.UTF8.GetString(SPAppTokenHeaderBytes) + Encoding.UTF8.GetString(SPAppTokenClaimsBytes);
            
            string[] accesTokenArray = accesToken.Split('.');
            byte[] accesTokenHeaderBytes = B64Helper.base64urldecode(accesTokenArray[0]);
            byte[] accesTokenClaimsBytes = B64Helper.base64urldecode(accesTokenArray[1]);
            accesToken = Encoding.UTF8.GetString(accesTokenHeaderBytes) + Encoding.UTF8.GetString(accesTokenClaimsBytes);

            
            Stream dataStream = endpointResponse.GetResponseStream();
            StreamReader reader = new StreamReader(dataStream);
            string responseFromServer = reader.ReadToEnd();


            Stream dataUserStream = currentUserResponse.GetResponseStream();
            StreamReader userReader = new StreamReader(dataUserStream);
            string userResponseFromServer = userReader.ReadToEnd();

            

            ViewBag.SPAppToken = SPAppToken;
            ViewBag.contextToken = contextToken;
            ViewBag.refreshToken = refreshToken;
            ViewBag.accesToken = accesToken;
            ViewBag.endpointResponse = endpointResponse;
            ViewBag.responseFromServer = responseFromServer;
            ViewBag.userResponseFromServer = userResponseFromServer;      
            return View(data);*/

            #endregion

            #region Storer le SPuser ainsi que les propriétés du futur MVC User dans TempData
            TempData["currentUser"] = spUser;
            TempData["userProperties"] = userProperties;
            #endregion

            //#region Rediriger vers le Controller d'Inscription/Gestion des Utilisateurs
            //return RedirectToAction("Register");
            //#endregion
            #region Si l'Utilisateur n'est pas inscrit.           
            var mvcUser = UserManager.FindByName(spUser.LoginName);
            if (mvcUser == null)
            {
                mvcUser = new ApplicationUser { UserName = spUser.LoginName, Email = spUser.Email };
                var result =  UserManager.Create(mvcUser, WebConfigHelper.getDummyPasswordFromWebConfig());
                if (result.Succeeded)
                {
                    mvcUser.SharePointId = spUser.Id;
                    mvcUser.DisplayName = spUser.Title;
                    mvcUser.RefreshToken = userProperties.Get("RefreshToken");
                    mvcUser.TargetRealm = userProperties.Get("TargetRealm");
                    mvcUser.Ressource = userProperties.Get("Ressource");
                    mvcUser.SecurityTokenServiceUrl = userProperties.Get("SecurityTokenServiceUrl");
                    mvcUser.TargetHost = userProperties.Get("TargetHost");
                    mvcUser.TargetPrincipalName = userProperties.Get("TargetPrincipalName");
                    UserManager.Update(mvcUser);
                    SignInManager.SignIn(mvcUser, isPersistent: false, rememberBrowser: false);

                    // Pour plus d'informations sur l'activation de la confirmation du compte et la réinitialisation du mot de passe, consultez http://go.microsoft.com/fwlink/?LinkID=320771
                    // Envoyer un message électronique avec ce lien
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);

MvcSpAppWeb/Controllers/SpListInfoController.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MvcSpAppWeb.Models;
using MvcSpAppWeb.CodeHelper;
using MvcSpAppWeb.Config;

namespace MvcSpAppWeb.Controllers
{
    [Authorize]
    public class SpListInfoController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: SpListInfo
        public ActionResult Index()
        {
            List<SpListMetadataModel> listModel = SpHelper.getAllSpLists(UserManager.FindById(User.Identity.GetUserId()), UserManager, Configuration.hostwebUrl);
            return View(listModel);
        }

        // GET: SpListInfo/Details/5
        public ActionResult Details(string id)
        {
            List<Dictionary<string, string>> spListItemsMetadatas = SpHelper.getSpListById(UserManager.FindById(User.Identity.GetUserId()), UserManager, id, Configuration.hostwebUrl);
            List<string> itemsList = new List<string>();
            #region Put All Items in one Single List
            int itemFieldsCount = 0;
            for (int i = 0; i < spListItemsMetadatas.Count; i++)
            {
                Dictionary<string, string> currendico = spListItemsMetadatas[i];
                if (i == 0)
                {
                    itemFieldsCount = currendico.Count;

                    foreach (var item in currendico)
                    {
                        itemsList.Add(item.Key);
                    }

                }
                foreach (var item in currendico)
                {
                    itemsList.Add(item.Value);
                }

            }
            #endregion
            ViewBag.itemFieldsCount = itemFieldsCount;
            return View(itemsList);
        }

        // GET: SpListInfo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SpListInfo/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SpListInfo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SpListInfo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: SpListInfo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SpListInfo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcSpAppWeb/Views/Home/About.cshtml
@model MvcSpAppWeb.ViewModels.AboutViewModel
@{
    ViewBag.Title = "About";
}
<div class="container">
    <div class="row">
        <div class="col-md-7 col-xs-10">
            <div class="well panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        @*<div class="col-xs-12 col-sm-4 text-center">
                            <img src="@Model.PictureUrl.value" alt="" class="center-block img-circle img-thumbnail img-responsive">
                            <ul class="list-inline ratings text-center" title="Ratings">
                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                            </ul>
                        </div>*@
                        <!--/col-->
                        <div class="col-xs-12 col-sm-8">
                            <h2>@Html.DisplayFor(m => m.DisplayName)</h2>
                            <p><strong>Email: </strong>@Html.DisplayFor(m => m.Email)</p>
                            <p><strong>SharePoint Id: </strong>@Html.DisplayFor(m => m.SharePointId)</p>
                            <p>
                                <strong>Skills: </strong>
                                <span class="label label-info tags">html5</span>
                                <span class="label label-info tags">css3</span>
                                <span class="label label-info tags">jquery</span>
                                <span class="label label-info tags">bootstrap3</span>
                            </p>
                        </div>
                        <!--/col-->
                        <div class="clearfix"></div>
                        <div class="col-xs-12 col-sm-4">
                            <h2><strong>@Model.HostWebListCount.value Listes </strong></h2>
                            <p><small>Listes SharePoint</small></p>
                            @Html.ActionLink("Voir toutes les listes", "Index", "SpListInfo", routeValues: null, htmlAttributes: new { @class = "btn btn-info" })
                        </div>
                        <!--/col-->
                        @*<div class="col-xs-12 col-sm-4">
                            <h2><strong>245</strong></h2>
                            <p><small>Following</small></p>
                            <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>
                        </div>
                        /col
                        <div class="col-xs-12 col-sm-4">
                            <h2><strong>43</strong></h2>
                            <p><small>Snippets</small></p>
                            <button type="button" class="btn btn-primary btn-block"><span class="fa fa-gear"></span> Options </button>
                        </div>*@
                        <!--/col-->
                    </div>
                    <!--/row-->
                </div>
                <!--/panel-body-->
            </div>
            <!--/panel-->
        </div>
        <!--/col-->
        <!--col-->
        <div class="col-md-5 col-xs-10">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li class="active"><a href="#rToken" role="tab" data-toggle="tab">RefreshToken</a></li>
                <li><a href="#aToken" role="tab" data-toggle="tab">AccessToken</a></li>
                <li><a href="#aOaToken" role="tab" data-toggle="tab">AppOnlyAccessToken</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active" id="rToken">@Model.RefreshToken</div>
                <div class="tab-pane" id="aToken">@Model.AccessToken</div>
                <div class="tab-pane" id="aOaToken">@Model.AppOnlyAccessToken</div>
            </div>
        </div>
        <!--/col-->
    </div>
    <!--/row-->
</div>
<!--/container-->

MvcSpAppWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "MVC SP APP Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    3727 rue du frère André<br />
    Montréal, H3v1B2<br />
    <abbr title="Phone">P:</abbr>
    438.345.3292
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@office365-apps.com.com">office365-apps.com</a><br />
</address>

MvcSpAppWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
<h1>Cette page n'est utilisée que dans d'etablir un single sign on entre SharePoint et l'App</h1>    
</div>
<div class="row">   
</div>